### ISSUE TITLE
PrivateWin10 - nothing happens

### ISSUE THREAD

**Issue by necros2k7** [mirinsoft/Roboget#1]
Nothing happens while trying to download latest release using this lnk - 
Link3=GetPortable|https://github.com/DavidXanatos/priv10/releases|M

**Comment by Belim** [comment]
I've updated the package 
https://github.com/mirinsoft/Roboget/blob/master/packages/PrivateWin10.rgp

You can update it through Robotget > Right Sidebar "Update"
